//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pasteleria_dd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int Id { get; set; }
        public string Tamanio { get; set; }
        public string Sabor { get; set; }
        public string Relleno { get; set; }
        public string Foto { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string Datos_extra { get; set; }
        public string correo_electronico { get; set; }
    }
}
